project:
  type: website
  output-dir: docs

website:
  title: "Brody Regan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
      - hobbies.qmd
  

format:
  html:
    theme: 
    - yeti
    - styles.scss
    mainfont: Raleway
    toc: true
    page-layout: full

editor: visual

